const HotelNamesData = [
  "Secret Point Hotel",
  "Twin Dome Motel",
  "Triple Landscape Hotel",
  "Sublime Cliff Hotel",
  "Scarlet Harbor Hotel",
  "King's Palace Hotel",
  "Rose Motel",
  "Sapphire Suites",
  "Smile Hotel",
  "Country Home",
  "Regal Orb Residence Inn",
  "Winter Panorama Resort",
  "Historic Lion Resort",
  "Twin Vertex Hotel",
  "Peaceful Market Hotel",
  "Double Sanctuary Resort",
  "Antiquity Hotel",
  "Oceanside Resort",
  "Universe Motel",
  "Esport Resort",
  "Nova Hotel",
  "Stone Lion Inn",
  "Days Hotel",
  "La Vista Hotel",
  "Scottish Inn",
  "Marquis Plaza & Suites",
  "Super Deluxe Inn & Suites",
  "Inoku hotel",
  "Thompson House",
  "Catfish Creek Fishing Cabins",
  "Athens Residence Hotel",
  "Goldmoor Inn",
  "Mottelers Thunderbird Motel",
  "Cap'n Jack's Waterfront Inn",
  "Suites At Bellevue Square",
  "Pelham Hotel",
  "Commander Hotel",
  "Lady Of The Lake B & B",
  "Whitefish Lodge & Suites",
  "Trails End Motel",
  "Ocean Air Motel",
  "Bar C Resort & Campground",
  "Johnson's Resort",
  "Monrovia Motor Inn",
  "Arcadia Resort & Restaurant",
  "Swan Point Inn",
  "South Court Inn",
  "Nordick's B & B",
  "Old Carrabelle Hotel",
  "Summer Wind Resort",
];

const hotelNameData = [
  'Smile Hotel',
  'Secret Point Hotel',
  'Regal Orb Residence Inn',
  'Historic Lion Resort',
  'Twin Vertex Hotel',
  'Oceanside Resort',
  'Stone Lion Inn',
  'Days Hotel',
  'Catfish Creek Fishing Cabins',
  'Mottelers Thunderbird Motel',
  'Lady Of The Lake B & B',
  'Trails End Motel',
  'Arcadia Resort & Restaurant',
  'South Court Inn',
  'Old Carrabelle Hotel',
  'Summer Wind Resort',
  'Sublime Cliff Hotel',
  'Triple Landscape Hotel',
  'Peaceful Market Hotel',
  'Esport Resort',
  'Marquis Plaza & Suites',
  'Super Deluxe Inn & Suites',
  'Inoku Hotel',
  'Athens Residence Hotel',
  'Goldmoor Inn',
  'Suites At Bellevue Square',
  'Commander Hotel',
  'Whitefish Lodge & Suites',
  'Swan Point hotel',
  "King's Palace Hotel",
  'Rose Motel',
  'Winter Panorama Resort',
  'Double Sanctuary Resort',
  'La Vista Hotel',
  'Scottish Inn',
  'Pelham Hotel',
  'Bar C Resort & Campground',
  "Johnson's Resort",
  "Nordick's B & B",
  'Twin Dome Motel',
  'Scarlet Harbor Hotel',
  'Sapphire Suites',
  'Country Home',
  'Antiquity Hotel',
  'Universe Motel',
  'Nova Hotel',
  'Thompson House',
  "Cap'n Jack's Waterfront Inn",
  'Ocean Air Motel',
  'Monrovia Motor Inn'
]